openapi: 3.0.0
info:
  title: Ecommerce API
  version: 1.1.0
  description: API docs for the ecommerce backend

paths:
  /api/auth/register:
    post:
      summary: Register user (sends email OTP)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered

  /api/auth/verify-email:
    post:
      summary: Verify email using OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, code]
              properties:
                email:
                  type: string
                  format: email
                code:
                  type: string
      responses:
        '200':
          description: Email verified

  /api/auth/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful

  /api/auth/logout:
    post:
      summary: Logout user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful

  /api/auth/me:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user

  /api/auth/forgot-password:
    post:
      summary: Start password reset
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: If the email exists, password reset instructions were sent

  /api/auth/reset-password:
    post:
      summary: Reset password using token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token, password]
              properties:
                token:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Password reset

  /api/products:
    get:
      summary: List products
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: Category ObjectId
        - in: query
          name: q
          schema:
            type: string
      responses:
        '200':
          description: Product list
    post:
      summary: Create product (admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpsertRequest'
      responses:
        '201':
          description: Product created

  /api/products/{id}:
    get:
      summary: Get product by id
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Product found
    put:
      summary: Update product (admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpsertRequest'
      responses:
        '200':
          description: Product updated
    delete:
      summary: Delete product (admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Product deleted

  /api/cart:
    get:
      summary: Get cart for current user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart

  /api/cart/add:
    post:
      summary: Add item to cart
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [productId]
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
                  minimum: 1
      responses:
        '200':
          description: Item added

  /api/cart/update:
    put:
      summary: Update cart (single item quantity or replace full items)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartUpdateRequest'
      responses:
        '200':
          description: Cart updated

  /api/cart/remove/{productId}:
    delete:
      summary: Remove item from cart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item removed

  /api/cart/clear:
    delete:
      summary: Clear cart
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cart cleared

  /api/users/profile:
    get:
      summary: Get own profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile
    put:
      summary: Update own profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateRequest'
      responses:
        '200':
          description: Profile updated
    delete:
      summary: Delete own profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile deleted

  /api/addresses:
    post:
      summary: Create address
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '201':
          description: Address created
    get:
      summary: List addresses
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Address list

  /api/addresses/{id}:
    put:
      summary: Update address
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressRequest'
      responses:
        '200':
          description: Address updated
    delete:
      summary: Delete address
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Address deleted

  /api/categories:
    get:
      summary: List active categories (public)
      responses:
        '200':
          description: Category list
    post:
      summary: Create category (admin)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequest'
      responses:
        '201':
          description: Category created

  /api/categories/{id}:
    put:
      summary: Update category (admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryRequest'
      responses:
        '200':
          description: Category updated
    delete:
      summary: Delete category (admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Category deleted

  /api/reviews:
    post:
      summary: Create review (auth)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewRequest'
      responses:
        '201':
          description: Review created

  /api/reviews/{id}:
    get:
      summary: List reviews for product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Product ObjectId
      responses:
        '200':
          description: Review list
    delete:
      summary: Delete review (owner/admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Review deleted

  /api/orders:
    post:
      summary: Create order
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreateRequest'
      responses:
        '201':
          description: Order created

  /api/orders/my-orders:
    get:
      summary: Get current user's orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Order list

  /api/orders/{id}:
    get:
      summary: Get order by id (owner/admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      responses:
        '200':
          description: Order details

  /api/orders/{id}/status:
    put:
      summary: Update order status (admin)
      security:
        - bearerAuth: []
      parameters:
        - $ref: '#/components/parameters/ObjectIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderStatus:
                  type: string
                paymentStatus:
                  type: string
      responses:
        '200':
          description: Order updated

  /api/payments/create:
    post:
      summary: Create payment session
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [orderId, paymentMethod]
              properties:
                orderId:
                  type: string
                paymentMethod:
                  type: string
      responses:
        '201':
          description: Payment created

  /api/payments/verify:
    post:
      summary: Verify payment using signature
      description: Signature must be HMAC-SHA256("{orderId}:{paymentId}") with PAYMENT_WEBHOOK_SECRET
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [orderId, paymentId, signature]
              properties:
                orderId:
                  type: string
                paymentId:
                  type: string
                signature:
                  type: string
      responses:
        '200':
          description: Payment verified

  /api/payments/{orderId}:
    get:
      summary: Get payment status for order
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Payment status

  /api/admin/users:
    get:
      summary: List users (admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User list

  /api/admin/orders:
    get:
      summary: List orders (admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Order list

  /api/admin/dashboard-stats:
    get:
      summary: Dashboard stats (admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Stats

  /api/admin/promote:
    post:
      summary: Promote user to admin
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [userId]
              properties:
                userId:
                  type: string
      responses:
        '200':
          description: User promoted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    ObjectIdParam:
      in: path
      name: id
      required: true
      schema:
        type: string

  schemas:
    RegisterRequest:
      type: object
      required: [name, email, password]
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
        phone:
          type: string

    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    ProfileUpdateRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string

    AddressRequest:
      type: object
      properties:
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        state:
          type: string
        postalCode:
          type: string
        country:
          type: string
        phone:
          type: string

    CategoryRequest:
      type: object
      properties:
        name:
          type: string
        slug:
          type: string
        isActive:
          type: boolean

    ProductUpsertRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        images:
          oneOf:
            - type: array
              items:
                type: string
            - type: string
        categoryId:
          type: string
          description: ObjectId, slug, or category name

    CartUpdateRequest:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
        items:
          type: array
          items:
            type: object
            required: [productId, quantity]
            properties:
              productId:
                type: string
              quantity:
                type: integer
                minimum: 1

    ReviewRequest:
      type: object
      required: [productId, rating]
      properties:
        productId:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        title:
          type: string
        body:
          type: string

    OrderCreateRequest:
      type: object
      required: [items, paymentMethod]
      properties:
        items:
          type: array
          minItems: 1
          items:
            type: object
            required: [productId, quantity]
            properties:
              productId:
                type: string
              quantity:
                type: integer
                minimum: 1
        shippingAddress:
          type: object
          properties:
            fullName:
              type: string
            phone:
              type: string
            addressLine1:
              type: string
            city:
              type: string
            state:
              type: string
            postalCode:
              type: string
            country:
              type: string
        paymentMethod:
          type: string
          enum: [COD, RAZORPAY, STRIPE]
        paymentId:
          type: string
          description: Optional external payment ID
